### ISSUE TITLE
[Samples][GTK] Allcontrols/TicTacToe

### ISSUE THREAD

**Issue by SergejDK** [fsprojects/Fabulous#459]
TicTacToe/AllControls GTK throughs a nullreferenceexception at start.

**Comment by SergejDK** [comment]
The issue happens when using `NavigationPage`.

I think this will be handled with next update of XF: [https://github.com/xamarin/Xamarin.Forms/pull/6462](https://github.com/xamarin/Xamarin.Forms/pull/6462)

@TimLariviere 
or do you think that would be an issue on our side? The PR looks a lot like the problem here.

**Comment by TimLariviere** [comment]
@SergejDK Just ran into this issue. You're right, it's the same issue that is fixed in the Xamarin.Forms PR.
We can wait for the fix to come out.

**Comment by SergejDK** [comment]
@TimLariviere 
normally this was planned for 4.1 but was moved to 4.2 so currently the issue is still there... Thought it will be in 4.1.
We have to wait for 4.2 then.
